### ISSUE TITLE
"Trinket ready" message and sound

### ISSUE THREAD

**Issue by Rerox-WoW** [Rottenbeer/ItemRack#109]
ItemRack does a sound and on screen message when a trinket CD is ready.
Thats's fine, but zunfortunately this Message and sound is not customizable (e.g. change Sound or Messagecolor) and can also not be turned off. (or I could not find the switch).
Any chance we get broader config options in the tool?

**Comment by btnmasher** [comment]
I don't think the maintainer has any intention on adding features, it seems like they only wanted to get the port to Classic working and that's it. If you wish to change the sound, you can do so here:

https://github.com/Rottenbeer/ItemRack/blob/c6cbe6e95b6b78dfdca15b532ff6d57cab7f27ad/ItemRack/ItemRack.lua#L1597

Change the SOUNDKIT value there, here's the file where these are defined (wow.tools link) [SoundKitConstants.lua](https://wow.tools/casc/file/chash?contenthash=178b8927eb3a7095f76cf22caad6ed51&filedataid=1665034&buildconfig=bf24b9d67a4a9c7cc0ce59d63df459a8&cdnconfig=2b5b60cdbcd07c5f88c23385069ead40&filename=soundkitconstants.lua)

**Comment by Rerox-WoW** [comment]
Great, thanks for the hint!

**Comment by Rottenbeer** [comment]
The maintainer is a one person show and does not play WoW anymore, so I do not develop any features I'm sorry.
I'm merging pull requests though, if I find time ;)
