### ISSUE TITLE
Trinket on CD triggers Mounted set

### ISSUE THREAD

**Issue by eplgr** [Rottenbeer/ItemRack#113]
Everything was working fine, and one day (probably after an update?) this thing started to happen.

Context: my raid set has Renataki and BHB + all my raid gear. My Mount set has all empty slots + carrot in my BHB slot.

Problem: When I use an activable trinket (renataki in this case), ItemRack queues the trinket swap in that specific slot. 
And it keeps wanting to do that. If I try to equip Renataki, it keeps trying to to equip my carrot in there. If I equip anything else in there with no CD, it stays that way.

The "wheel" in the trinket menu turns red when all of this happens. I believe this is new as well.

**Comment by btnmasher** [comment]
Have you tried deleting and re-making your sets and seeing if this is still the case?

**Comment by eplgr** [comment]
No. I only tried deleting and re-making my Mount set and event.

Un-ticking "enable auto-queues" fixes the problem.
