### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Altoholic** [Rottenbeer/ItemRack#117]
3x [ADDON_ACTION_BLOCKED] AddOn 'ItemRack' tried to call the protected function 'AttemptToSaveBindings()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `AttemptToSaveBindings'
ItemRack\ItemRack-3.46.nil.lua:1910: in function `SetSetBindings'
ItemRack\ItemRack-3.46.nil.lua:465: in function `InitCore'
ItemRack\ItemRack-3.46.nil.lua:203: in function `func'
ItemRack\ItemRack-3.46.nil.lua:877: in function `OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

**Comment by Rottenbeer** [comment]
I guess it's a error when saving the hotkeys in combat and it should be fixed with 3.47
