### ISSUE TITLE
Talisman of Ephemeral Power is not being detected.

### ISSUE THREAD

**Issue by VulpesHD** [Rottenbeer/ItemRack#118]
Talisman of Ephemeral Power is not being detected by ItemRack.
I have it in my bags, but the addon does not show it.
Images: [https://imgur.com/a/BZTBKR7](https://imgur.com/a/BZTBKR7)

**Comment by facefetc** [comment]
Same for Onyxia Scale Cloak.
Thought it maybe had something to do with never banking the item, so it forgot it was there, but that didn't help.

It has been like this for the past ... uh, not entirely sure, but say 2-3 weeks. Roughly ish.

![image](https://user-images.githubusercontent.com/69805114/90407132-67ddbf00-e0a6-11ea-93cd-32379c2640ad.png)

**Comment by VulpesHD** [comment]
I found out what caused it, and its not an issue with the addon.
If you alt + left click an item in the hover over menu, then it will remove it from the addon.
So just hold ALT and hover over an item then you can left click your missing items, and they will show up again. (You can do it in the character menu too) (Example: https://i.imgur.com/h4TFRz4.gif)
Will close the thread.
