### ISSUE TITLE
Selecting a set frame disappears with Square Minimap Buttons's fading

### ISSUE THREAD

**Issue by Eyji** [Rottenbeer/ItemRack#119]
Hello!

I am using ElvUI with ProjectAzilroka's awesome feature which converts every minimap buttons into a square bar. Unfortunately, I have an issue when trying to select a set : the bar disappears and the selecting frame with it. I don't encounter this issue with other addons.

- You can find [here a video demonstrating this issue](https://streamable.com/wpw0hr)
- The addon is called "[ProjectAzilroka](https://www.tukui.org/addons.php?id=79)" 
- The feature is called "Square Minimap Buttons"
![image](https://user-images.githubusercontent.com/10639815/90511415-b483d180-e15c-11ea-9e42-d6c8b2c99325.png)

**Comment by Rottenbeer** [comment]
Recheck with 3.64 please
