### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SegoItCh** [Rottenbeer/ItemRack#120]
Message: Interface\AddOns\ItemRack\ItemRack-3.46.nil.lua:1140: Attempt to access forbidden object from code tainted by an AddOn
Time: Tue Aug 25 01:06:45 2020
Count: 1
Stack: Interface\AddOns\ItemRack\ItemRack-3.46.nil.lua:1140: Attempt to access forbidden object from code tainted by an AddOn
Interface\AddOns\ItemRack\ItemRack.lua:877: in function `OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: self = ItemRackFrame {
0 = <userdata>
}
elapsed = 0.014000
timerPool = <table> {
elapsed = -0.004000
rep = 1
func = <function> defined @Interface\AddOns\ItemRack\ItemRack.lua:1138
delay = 0.250000
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
1 = "CooldownUpdate"
2 = "CheckForMountedEvents"
3 = "MenuMouseover"
}
(for control) = 3
_ = 3
name = "MenuMouseover"

**Comment by Rottenbeer** [comment]
Can you be more verbose?
How can the issue be reproduced?
