### ISSUE TITLE
-- stop queue here --

### ISSUE THREAD

**Issue by Rover-33** [Rottenbeer/ItemRack#124]
line "-- stop queue here --" disapeared when set enable per-set queues

**Comment by Rottenbeer** [comment]
@brzGatsu can you have a look please, I guess you implemented the PR?

**Comment by brzGatsu** [comment]
When enabling the feature you need to redo your queues for every set, so the -stop queue- entry usually moves to the bottom of the list - did you scroll all the way to the bottom and check the entire list? I cannot reproduce the issue.

**Comment by Rover-33** [comment]
I think I found it!
First Reset Everything
Uncheck Allow empty slots
Go to Queue tab and check any slot
