### ISSUE TITLE
How to prevent auto-queuing trinkets when manually changing them?

### ISSUE THREAD

**Issue by Jakobud** [Rottenbeer/ItemRack#127]
I have a couple trinkets setup with Auto-queuing:

1. Earthstrike
2. Hand of Justice

There are some situations where I need to use Hand of Justice even though Earthstrike is ready to use (or has less than 30 seconds on it's CD).

When I manually change to Hand of Justice, ItemRack automatically changes it back to Earthstrike.

Is there any way to prevent or pause the Auto-queuing when I manually change trinkets? I don't want to just disable or turn off the Auto-queuing because it's super useful.

An example of where this would be used: Lets say in a raid you have a trash pack to pull right before a boss. The trash pack I would say takes only 20 seconds to kill. Earthstrike is ready to use so ItemRack uses Auto-queue to equip it. But I would rather save Earthstrike for the boss and use Hand of Justice on the trash pack. Auto-queuing prevents this.

Another example would be if you are about to fight a raid boss that usually takes approximately 40 seconds to kill. If ItemRack auto-queue switches to your trinket right before the fight since it has 30 seconds CD left on it, then for 30 of those 40 seconds, the trinket cannot even be used. It would have been better to just keep the Hand of Justice trinket equipped.

Is there a way around this? I'm thinking maybe I need to make per-set auto-queues or something. I'm not sure.

**Comment by nerolite** [comment]
Being able to manually override the queue - while reverting to the queue after the trinket has been used - is such a needed feature, indeed. It could make the auto-queue feature much more seamless (instead of having to pause and then remember to unpause before swapping).

**Comment by Jakobud** [comment]
How do you pause/unpause an auto-queue? I've seen the pause setting but it seems like you have to choose a specific trinket to pause on? I don't really understand the purpose of it I guess.

Is it possible to bind a hotkey to the auto queue to pause/unpause the whole thing ?

**Comment by nerolite** [comment]
To pause you simply alt-click the slot. I cannot answer the rest.

**Comment by Cyanokaze** [comment]
Set Trinket "Hand of Justice" as "Pause"

**Comment by Jakobud** [comment]
So if I set Hand of Justice to Pause what does that do exactly? Does that mean when I manually switch to it, it will pause the auto-queue?

What happens if I have 3 trinkets set in this order:

1. Earthstrike
2. Hand of Justice (set on Pause)
3. ZG trinket

Will the auto-queue pause on HoJ if its going through the queue like normal? Or will it only pause if I manually switch to HoJ?

Thanks,

**Comment by Cyanokaze** [comment]
> So if I set Hand of Justice to Pause what does that do exactly? Does that mean when I manually switch to it, it will pause the auto-queue?
> 
> What happens if I have 3 trinkets set in this order:
> 
> 1. Earthstrike
> 2. Hand of Justice (set on Pause)
> 3. ZG trinket
> 
> Will the auto-queue pause on HoJ if its going through the queue like normal? Or will it only pause if I manually switch to HoJ?
> 
> Thanks,

If you choose 'pasue' then you can't get auto-equip by addon. Caused by addon don't know when you need restore the auto-equip.

**Comment by VincentVancalbergh** [comment]
> If you choose 'pasue' then you can't get auto-equip by addon. Caused by addon don't know when you need restore the auto-equip.

I think @Jakobud thinks the Alt+Click will pause only the trinket. But it pauses the whole queue on that slot. Right?

**Comment by Moezenka** [comment]
Is there a way to pause this using a macro of sorts?
Or perhaps toggle it using a macro would be even better.
