### ISSUE TITLE
Add tooltip info for items

### ISSUE THREAD

**Issue by wentsa** [Rottenbeer/ItemRack#129]
It would be nice to add info into item's tooltip to see if it is involved in any of your saved sets.

"Sets: PvE, Viscidus" (if this item is saved for sets with name "PvE" and "Viscidus") or "Sets: -" (if this item doesnt appear in any saved sets.

This would help organize lots of items in bag, bank etc to see if you really need them.

**Comment by Rottenbeer** [comment]
![image](https://user-images.githubusercontent.com/2014982/119015421-2d88b180-b999-11eb-816c-3022489c1850.png)

Should be in there actually

**Comment by Rottenbeer** [comment]
Don't forget to enable it in the options though.
