### ISSUE TITLE
After Cast spams chat

### ISSUE THREAD

**Issue by IsoPippel** [Rottenbeer/ItemRack#13]
Hello,
I tried using After Cast event, but instead of perfoming the action,
it started spamming the lua code into chat (for which I was promptly silenced for).

Did I do something wrong, or is it a known bug?
```
local spell = "Gouge"
local set = "Dagger"
if arg1=="player" and arg2==spell then
  EquipSet(set)
end

--[[This event will equip "Name of set" when "Name of spell" has finished casting.  Change the names for your own use.]]
```

**Comment by Rottenbeer** [comment]
Since I'm not the original author and I don't have experience with the custom events, I can not support you.
