### ISSUE TITLE
Error in classic AV

### ISSUE THREAD

**Issue by Speaker1264** [Rottenbeer/ItemRack#133]
Not sure what is causing this, but I keep getting this error whenever I'm in Alterac Valley in Classic wow.  I have a macro that is just /itemrack equip set, and my best guess is it seems to happen whenever I click the macro and am hitting movement keys or jumping while swapping between gear sets.

Message: Interface\AddOns\ItemRack\ItemRackEquip.lua:288: script ran too long
Time: Sun Nov  8 05:11:30 2020
Count: 1
Stack: Interface\AddOns\ItemRack\ItemRackEquip.lua:288: script ran too long
[C]: ?
Interface\AddOns\ItemRack\ItemRackEquip.lua:288: in function `MoveItem'
Interface\AddOns\ItemRack\ItemRackEquip.lua:216: in function `IterateSwapList'
Interface\AddOns\ItemRack\ItemRackEquip.lua:127: in function `EquipSet'
Interface\AddOns\ItemRack\ItemRack.lua:1936: in function `?'
Interface\FrameXML\ChatFrame.lua:4695: in function <Interface\FrameXML\ChatFrame.lua:4642>
[C]: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4356: in function <Interface\FrameXML\ChatFrame.lua:4355>
[C]: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:2783: in function <Interface\FrameXML\ChatFrame.lua:2776>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `UseAction'
Interface\FrameXML\SecureTemplates.lua:338: in function `handler'
Interface\FrameXML\SecureTemplates.lua:616: in function <Interface\FrameXML\SecureTemplates.lua:564>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:266: in function <Interface\FrameXML\SecureHandlers.lua:263>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:296: in function <Interface\FrameXML\SecureHandlers.lua:279>
(tail call): ?

Locals:

**Comment by Rottenbeer** [comment]
Please retest with 3.64
