### ISSUE TITLE
Minimap button does not recognize resized minimap

### ISSUE THREAD

**Issue by Noino** [Rottenbeer/ItemRack#134]
If the minimap is resized (for exmple with elvui), the button does not follow the map outline when dragged, rather goes through the middle of it if minimap is made larger.

![image](https://user-images.githubusercontent.com/504736/98476230-b1016300-21fe-11eb-8cbe-50a580eea9da.png)

**Comment by nfgallimore** [comment]
Yeah, there is even a feature for "use square minimap" but with ElvUI it still doesn't fit right. I want the icon enabled, but this makes me not want it on. It's literally in the way of debuffs.
