### ISSUE TITLE
Item not found

### ISSUE THREAD

**Issue by zmancarl** [Rottenbeer/ItemRack#136]
Unexpectedly Itemrack stops seeing a particular item in buttons. Resetting buttons does not resolve the issue. Only full Itemrack reset does.

**Comment by Rottenbeer** [comment]
"My Item does not show up in the gear menu"

You probably Alt+leftclicked on it, to revert, just hold Alt and hover over the item (see https://github.com/Rottenbeer/ItemRack/issues/118)

From the FAQ on curseforge.

**Comment by zmancarl** [comment]
Thank you, sorry for having bothered with it.
