### ISSUE TITLE
Rogue Stealth "unequip on leaving stance" does not work if attacking or using skill

### ISSUE THREAD

**Issue by IsoPippel** [Rottenbeer/ItemRack#14]
Rogue Stealth "unequip on leaving stance" does not seem work if attacking, using skill or being attacked (thus unstealthing).
(Stance id: 1)

**Comment by gcaliber** [comment]
Are you trying to unequip a weapon?

**Comment by IsoPippel** [comment]
I'm trying to switch from my "stabby stabby" itemset back to my "default" itemset, which includes different weapon for main hand.

**Comment by Rottenbeer** [comment]
Switching weapons in combat is not working, that's a known issue right now.

**Comment by Rottenbeer** [comment]
Retest with 3.19 please, should not grey out anymore
