### ISSUE TITLE
Feature Request: show which set an item is in tooltip

### ISSUE THREAD

**Issue by joe-hart** [Rottenbeer/ItemRack#142]
I have multiple sets configured in ItemRack and it's a little confusing making sure I have all the right gear in my bags so I can switch between the various sets I use in a raid. Would it be possible to add something to the item tooltip that indicates which set(s) a piece of gear is used for? Something similar to how when you favorite something in AtlasLoot it shows up on the tooltip would be very handy.

**Comment by Rottenbeer** [comment]
duplicate to #129
