### ISSUE TITLE
Creating menu buttons in macros

### ISSUE THREAD

**Issue by drlkf** [Rottenbeer/ItemRack#143]
Hello,

I would like to replace the minimap button with an action bar button through a macro. The closest I got to it is by calling this:

```/run ItemRack.BuildMenu()```
or this
```/click ItemRackMinimapFrame```

however this doesn't follow the cursor so the menu immediately disappears because the cursor is not in range. Is it possible to do this in the current state or are modifications needed ? I also have the same question about item slots, I would like to put buttons in an action bar that would open up the same menu as buttons created by alt-clicking item slots in the character sheets.

Cheers !

**Comment by Rottenbeer** [comment]
I don't think that's possible right now.
