### ISSUE TITLE
Bug when change stuff in combat

### ISSUE THREAD

**Issue by Felindea** [Rottenbeer/ItemRack#15]
When i change my stuff with a macro IN COMBAT
like for exemple 
/cast Posture défensive
/itemrack equip Def

My weapon is stuck (grey) and i can't change it anymore until i disconnect, i also have an error in chat
![aaa](https://user-images.githubusercontent.com/3396352/64740026-3e123480-d4f4-11e9-8b61-ad694b587b02.png)

**Comment by Rottenbeer** [comment]
Switching weapons in combat is not working, that's a known issue right now.

**Comment by Rottenbeer** [comment]
Retest with 3.15.

**Comment by dmoraBerlin** [comment]
Why is this closed? This is still a bug in Classic.

**Comment by Rottenbeer** [comment]
"the bug comes from the fact that the addon does not let us change weapons in combat"
