### ISSUE TITLE
TBC

### ISSUE THREAD

**Issue by kurtronshausen** [Rottenbeer/ItemRack#153]
Are you planning on maintaining a version of itemrack for TBC classic? I went ahead and made some changes here: https://github.com/kurtronshausen/itemrack

It's a pretty minimal amount of changes other than the backdrop stuff.  Think it's possible to release the same code for both? I guess the old xml and new xml could live side by side?

**Comment by Rottenbeer** [comment]
I will make it work for TBC I guess, but I don't have a plan right now when or how.
Did you test your changes on the beta server and live?

**Comment by houlia** [comment]
kurtonshausen's changes seemed to work for me,  Today, I copied my profile from Live onto the Beta server (client version 2.5.2.38598) and everything loaded up and sets switched okay.

**Comment by kurtronshausen** [comment]
I went ahead and created a new project on curseforge, since it looks like it will be mildly annoying to maintain both a classic era and tbc classic version.

**Comment by Rottenbeer** [comment]
@kurtronshausen please don't create a fork on this on curseforge without my consent..
I'll figure out how to generate two projects out of the same sources before TBC starts.

**Comment by kurtronshausen** [comment]
Sounds good. Removed.

**Comment by Rottenbeer** [comment]
https://www.curseforge.com/wow/addons/itemrack-classic/
I released two versions of itemrack today, one for classic and one for bcc.
If everything works it, packaging should work now for both projects.
Please help me out with testing both and give me feedback.

**Comment by houlia** [comment]
> 
> 
> https://www.curseforge.com/wow/addons/itemrack-classic/
> I released two versions of itemrack today, one for classic and one for bcc.
> If everything works it, packaging should work now for both projects.
> Please help me out with testing both and give me feedback.

I tested this version on TBC beta.  Seems to work well.  The only issue I have is with the Evocation event swap; it doesn't seem to work.  However, I believe this is a Blizzard limitation not an ItemRack issue.

**Comment by w1Ngx** [comment]
I installed the new TBC version, but noticed that although all itemsets are correct in the addon basically all menus (dropdown minimap and in charakterscreen) do not work, so I can't select the sets any more or swap items idividually. Also the itemrack screen doesnt have a background any more.

**Comment by tobbi007** [comment]
for the background just add

ItemRackOptions.lua Line 56 (Function ItemRackOpt.Onload(self))

`Mixin(ItemRackOptFrame, BackdropTemplateMixin)
	ItemRackOptFrame:SetBackdrop({
		bgFile = "Interface\\DialogFrame\\UI-DialogBox-Background-Dark", 
		edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border",
		tile = true,
		tileSize = 16,
		edgeSize = 16,
		insets = {left = 4, right = 4, top = 4, bottom = 4},
	})`

**Comment by w1Ngx** [comment]
I can confirm that it workks with 3.64 now - thanks for the fast response!
