### ISSUE TITLE
lua error (at login)

### ISSUE THREAD

**Issue by Altoholic** [Rottenbeer/ItemRack#154]
1x ItemRack\ItemRack-3.54.nil.lua:1937: Usage: SaveBindings(1||2)
[C]: in function `AttemptToSaveBindings'
ItemRack\ItemRack-3.54.nil.lua:1937: in function `SetSetBindings'
ItemRack\ItemRack-3.54.nil.lua:479: in function `InitCore'
ItemRack\ItemRack-3.54.nil.lua:213: in function <ItemRack\ItemRack.lua:208>

Locals:
(*temporary) = 251658242

**Comment by Rottenbeer** [comment]
Is this still an issue?

**Comment by Altoholic** [comment]
no :)
