### ISSUE TITLE
Unable to change 2nd ring

### ISSUE THREAD

**Issue by gcaliber** [Rottenbeer/ItemRack#17]
I can't figure out what caused this. I had a set with all the gear I normally wear, and whenever I tried to change my 2nd ring it kept automatically re-equipping the old one even if I changed the set and reloaded the ui. I had to disable the addon to change it.

**Comment by Rottenbeer** [comment]
Did you enable the auto queue feature on accident?

**Comment by gcaliber** [comment]
It is enabled by default. Turning it off does seem to fix it.
