### ISSUE TITLE
[Bug][Classic ERA] Lua error

### ISSUE THREAD

**Issue by waytoomuchgaming** [Rottenbeer/ItemRack#170]
at login ::

2x ItemRack\ItemRack-3.66.nil.lua:1935: Usage: SaveBindings(1||2)
[C]: in function `AttemptToSaveBindings'
ItemRack\ItemRack-3.66.nil.lua:1935: in function `SetSetBindings'
ItemRack\ItemRack-3.66.nil.lua:486: in function `InitCore'
ItemRack\ItemRack-3.66.nil.lua:222: in function <ItemRack\ItemRack.lua:216>

Locals:
(*temporary) = 1919251539

**Comment by Rottenbeer** [comment]
Can't reproduce, check if you installed the correct version.

**Comment by waytoomuchgaming** [comment]
with the last version (3.67) on a 1.13.7 server (ERA) ::

1x ItemRack\ItemRack-3.67.nil.lua:1939: Usage: SaveBindings(1||2)
[C]: in function `AttemptToSaveBindings'
ItemRack\ItemRack-3.67.nil.lua:1939: in function `SetSetBindings'
ItemRack\ItemRack-3.67.nil.lua:490: in function `InitCore'
ItemRack\ItemRack-3.67.nil.lua:226: in function <ItemRack\ItemRack.lua:220>

Locals:
(*temporary) = 1919251539

**Comment by waytoomuchgaming** [comment]
It's not 100% reproducible.
But when it happen, it's at login, and the itemrack bar is absent (the minimap/titan button is still there, tho, and functional - the character panel where you can directly change gear is still there and functional too; it's just the bar who's gone)

**Comment by Rottenbeer** [comment]
Please test with the two new alpha releases on https://www.curseforge.com/wow/addons/itemrack-classic/files/all

**Comment by waytoomuchgaming** [comment]
Here are the errors i got with alpha release ::

3x ItemRack\ItemRack-3.68.nil.lua:787: bad argument #2 to 'find' (string expected, got nil)
[C]: in function `find'
ItemRack\ItemRack-3.68.nil.lua:787: in function `PlayerCanWear'
ItemRack\ItemRack-3.68.nil.lua:995: in function `BuildMenu'
ItemRack\ItemRack-3.68.nil.lua:1730: in function `DockMenuToCharacterSheet'
ItemRack\ItemRack-3.68.nil.lua:1709: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = "Requires Level 10"
(*temporary) = nil
(*temporary) = "string expected, got nil"

*****

3x ItemRack\ItemRack-3.68.nil.lua:883: attempt to index field 'TimerPool' (a nil value)
ItemRack\ItemRack-3.68.nil.lua:883: in function `StartTimer'
ItemRack\ItemRack-3.68.nil.lua:1116: in function `BuildMenu'
ItemRack\ItemRack-3.68.nil.lua:1730: in function `DockMenuToCharacterSheet'
ItemRack\ItemRack-3.68.nil.lua:1709: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
name = "MenuMouseover"
delay = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'TimerPool' (a nil value)"

**Comment by Rottenbeer** [comment]
Please check those, they load properly for me
[ItemRack-3.67-bcc.zip](https://github.com/Rottenbeer/ItemRack/files/6604133/ItemRack-3.67-bcc.zip)
[ItemRack-3.67-classic.zip](https://github.com/Rottenbeer/ItemRack/files/6604134/ItemRack-3.67-classic.zip)

**Comment by waytoomuchgaming** [comment]
Fully working again, including ammo slot :)
TY!

**Comment by Rottenbeer** [comment]
Please test for a day or two and give me feedback afterwards, so that I can release it. I want to make sure the login error is gone, but never was able to reproduce it.

**Comment by waytoomuchgaming** [comment]
and then, out of the blue ::
1x ItemRack\ItemRack-3.68.nil.lua:1945: Usage: SaveBindings(1||2)
[C]: in function `AttemptToSaveBindings'
ItemRack\ItemRack-3.68.nil.lua:1945: in function `SetSetBindings'
ItemRack\ItemRack-3.68.nil.lua:233: in function `?'
ItemRack\ItemRack-3.68.nil.lua:198: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = 1919251539

**Comment by waytoomuchgaming** [comment]
i played 8 different characters these last 2 days, with no issue at all.
and on that rogue, at login, all of a sudden, i got it again.

**Comment by Rottenbeer** [comment]
Yeah it's a race basically and it just got way less common. Need to move it later I guess.

**Comment by Laumesis** [comment]
This is really rare and random: ItemRack on TBCC, v 3.68
```
Message: Interface\AddOns\ItemRack\ItemRack.lua:1946: Usage: SaveBindings(1|2)
Time: Fri Jun 25 18:18:28 2021
Count: 1
Stack: Interface\AddOns\ItemRack\ItemRack.lua:1946: Usage: SaveBindings(1|2)
[string "=[C]"]: in function `SaveBindings'
[string "@Interface\AddOns\ItemRack\ItemRack.lua"]:1946: in function `SetSetBindings'
[string "@Interface\AddOns\ItemRack\ItemRack.lua"]:233: in function `?'
[string "@Interface\AddOns\ItemRack\ItemRack.lua"]:198: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = 0
```

I suspect it is heavily timing dependant. Something fetched from server fast enough (or too slowly?) and things work fine?
