### ISSUE TITLE
[Bug][Classic ERA] ammo not manageable anymore

### ISSUE THREAD

**Issue by waytoomuchgaming** [Rottenbeer/ItemRack#171]
You can't select them in the "sets" tab.

**Comment by Rottenbeer** [comment]
https://youtu.be/jxOuAiMi_Hw
What doesn't work as expected?

**Comment by waytoomuchgaming** [comment]
With the alpha release, i can't test it anymore, because the addon breaks immediately, with new errors, whenever i over any slot in my character sheet.

Previously, i was not able to do what you do in the video: the ammo slot was not interactive.
I think it happened after a release - i remember using it previously (some of my old sets do have ammos selected).

**Comment by Rottenbeer** [comment]
I didn't change anything regarding the ammo slots in the alpha release, so no use in testing those.
I should work in the latest release as I show it in the video.
