### ISSUE TITLE
[Bug]ItemRack is not seeing the new bank slot added in pre-patch

### ISSUE THREAD

**Issue by savinedg** [Rottenbeer/ItemRack#172]
When I try to put items from inventory to bank using ItemRack, it fills up all of bank except the 7th bag slot and then complains bank is full. It seems like ItemRack is not seeing the 7th bag slot.

**Comment by wenqu** [comment]
@Rottenbeer 
Issue is related to the hardcoded amoutn of BankSlots:
https://github.com/Rottenbeer/ItemRack/blob/master/ItemRack/ItemRack.lua#L78
`ItemRack.BankSlots = { -1,5,6,7,8,9,10 }`

Maybe get the BankSlots from the constant
**NUM_BANKBAGSLOTS**

**Comment by savinedg** [comment]
> @Rottenbeer
> Issue is related to the hardcoded amoutn of BankSlots:
> https://github.com/Rottenbeer/ItemRack/blob/master/ItemRack/ItemRack.lua#L78
> `ItemRack.BankSlots = { -1,5,6,7,8,9,10 }`
> 
> Maybe get the BankSlots from the constant
> **NUM_BANKBAGSLOTS**

What if we just add 11 to that set? Like so:
`ItemRack.BankSlots = { -1,5,6,7,8,9,10,11 }`

**Comment by Rottenbeer** [comment]
Check 3.67, should be fixed now
