### ISSUE TITLE
Cannot use item rack in any way. Left click on minimap icon does nothing. Right click brings up LUA error. 

### ISSUE THREAD

**Issue by JennaTulwarts** [Rottenbeer/ItemRack#173]
Interface\AddOns\ItemRack\ItemRack.lua:1790: attempt to index global 'ItemRackOptFrame' (a nil value)
Time: Sun May 30 18:31:06 2021
Count: 1
Stack: Interface\AddOns\ItemRack\ItemRack.lua:1790: attempt to index global 'ItemRackOptFrame' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ItemRack\ItemRack.lua"]:1790: in function `ToggleOptions'
[string "@Interface\AddOns\ItemRack\ItemRack.lua"]:1769: in function `OnClick'
[string "@Interface\AddOns\Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:144: in function <...ce\AddOns\Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

As I said I cannot use ItemRack. Left regularly and with Alt or Ctrl does nothing. Right ckick and with Alt or Ctrl bring up this LUA error. I have deleted my WTF file and reinstalled the addon with the same results.

**Comment by Rottenbeer** [comment]
WoW Version? Client? Which ItemRack version did you install? Where did you get it?

**Comment by JennaTulwarts** [comment]
> 
> 
> WoW Version? Client? Which ItemRack version did you install? Where did you get it?


Most recent patch of TBC Classic. ItemRack version 3.66, installed from WowUp didn't work. Reinstalled with Curse with the same result.

**Comment by Rottenbeer** [comment]
Did you pick the TBC version from curseforge? There are 2 available to download

**Comment by JennaTulwarts** [comment]
Yes I did. It went from working perfectly to the LUA error.

**Comment by Rottenbeer** [comment]
Sounds like you don't have a ItemRackOptions folder in your Addon folder?
The addon works well in tbc, just tested it.

**Comment by Rottenbeer** [comment]
Can't reproduce.
