### ISSUE TITLE
No tree of life form?

### ISSUE THREAD

**Issue by goldenpipes** [Rottenbeer/ItemRack#175]
am i blind or is it not implemented yet?

In the meantime i have it working by looking for "buff" "tree of life"

**Comment by Rottenbeer** [comment]
[ItemRack-3.67-bcc.zip](https://github.com/Rottenbeer/ItemRack/files/6598683/ItemRack-3.67-bcc.zip)
Can you test this please?

**Comment by Rottenbeer** [comment]
Fixed with 3.68
