### ISSUE TITLE
Doesn't take in account gems on same equipment

### ISSUE THREAD

**Issue by aklm1e** [Rottenbeer/ItemRack#177]
Hi,

I have twice the same gear with different gems on it. 

When I switch equipments, itemrack toggle the gear I have equipped but do not respect the gems.

Is it possible to make it work like it was in classic with different enchants ?

Thanks

**Comment by Rottenbeer** [comment]
Afaik it also didn't work with different enchants.
Taking gems into account is no prio right now.

**Comment by Simon3** [comment]
Any chance to have a new look at this?
People will encounter this problem more and more with trash/boss gear swaps in raids, resistance gear with different gems/enchants etc. 
Really annoying for speedruns :/

**Comment by Simon3** [comment]
This seems fixed in latest version?
