### ISSUE TITLE
Lua error when changing button scale

### ISSUE THREAD

**Issue by OleBueker** [Rottenbeer/ItemRack#178]
`2x ItemRack\ItemRackButtons.lua:631: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ItemRackButton20:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@ItemRack\ItemRackButtons.lua"]:631: in function `ReflectMainScale'
[string "@ItemRackOptions\ItemRackOptions.lua"]:787: in function `UpdateSlider'
[string "@ItemRackOptions\ItemRackOptions.lua"]:769: in function `SliderValueChanged'
[string "*:OnValueChanged"]:3: in function <[string "*:OnValueChanged"]:1>
[string "=[C]"]: in function `SetValue'
[string "@ItemRackOptions\ItemRackOptions.lua"]:800: in function `NumberEditBoxOnEnter'
[string "*:OnEnterPressed"]:2: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = ItemRackButton20 {
 0 = <userdata>
 HotKey = ItemRackButton20HotKey {
 }
 NewActionTexture = <unnamed> {
 }
 Border = ItemRackButton20Border {
 }
 Flash = ItemRackButton20Flash {
 }
 icon = ItemRackButton20Icon {
 }
 AutoCastable = <unnamed> {
 }
 SpellHighlightAnim = <unnamed> {
 }
 SpellHighlightTexture = <unnamed> {
 }
 NormalTexture = ItemRackButton20NormalTexture {
 }
 FlyoutBorderShadow = ItemRackButton20FlyoutBorderShadow {
 }
 FlyoutBorder = ItemRackButton20FlyoutBorder {
 }
 Count = ItemRackButton20Count {
 }
 AutoCastShine = ItemRackButton20Shine {
 }
 FlyoutArrow = ItemRackButton20FlyoutArrow {
 }
 cooldown = ItemRackButton20Cooldown {
 }
 Name = ItemRackButton20Name {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = UIParent {
 variablesLoaded = true
 PixelSnapDisabled = true
 firstTimeLoaded = 1
 0 = <userdata>
}
(*temporary) = "BOTTOMLEFT"
(*temporary) = 557.618449
(*temporary) = 187.042704
`

**Comment by Rottenbeer** [comment]
Please retest with 4.2
