### ISSUE TITLE
Switching weapons in combat fails. 

### ISSUE THREAD

**Issue by erbthrowaway** [Rottenbeer/ItemRack#18]
Using itemrack to swap weapons in combat fails because of a "protected function".

```
ID: 1
Error occured in: AddOn: ItemRack
Count: 1
Message: Note: AddOn ItemRack attempted to call a protected function (PickupContainerItem()) during combat lockdown.
Debug:
   [C]: PickupContainerItem()
   ItemRack\ItemRackEquip.lua:276: MoveItem()
   ItemRack\ItemRackEquip.lua:198: IterateSwapList()
   ItemRack\ItemRackEquip.lua:113: EquipSet()
   ItemRack\ItemRack.lua:1189:
      ItemRack\ItemRack.lua:1126
Locals:
None
```
In the brief digging I did `PickupContainerItem()` does not look to be protected but there are some docs about calling it twice in the same tick causing the client issues. See: https://wowwiki.fandom.com/wiki/API_PickupContainerItem

**Comment by Rottenbeer** [comment]
There are rumors that it is a protected function in classic but I was not able to investigate this.
Can you have a look if you can add a delay between the calls and it might be fixable?

**Comment by Rottenbeer** [comment]
Retest with 3.15.

**Comment by cannonpalms** [comment]
@Rottenbeer 
Perhaps the bug should be fixed rather than outright removing the feature entirely. Additionally, to answer your question, no, `PickupContainerItem(...)` is not a protected function.

**Comment by Rottenbeer** [comment]
See discussion in https://github.com/Rottenbeer/ItemRack/pull/28
I guess the documentation is not up to date. 
I also tried adding delays between the pickup calls or trying autoequipitem() but it also does not work
