### ISSUE TITLE
Minimap button

### ISSUE THREAD

**Issue by LoopeeDK** [Rottenbeer/ItemRack#182]
I have no minimap button, so I cant seem to save any sets (Im using elv ui, tried to make the buttons appear default(unskin) and then reset buttons to no avail.)

**Comment by fultonm** [comment]
I also have no minimap button.

**Comment by Rottenbeer** [comment]
/itemrack opt and enable the minimap button in the options

**Comment by fultonm** [comment]
Since the quick start guide references nothing but the button to interact with functionality, I would suggest enabling the button by default or calling out how to enable it in the quick start section.
