### ISSUE TITLE
1.14 - backdrop change

### ISSUE THREAD

**Issue by Slivo-fr** [Rottenbeer/ItemRack#188]
Hi,

With the 1.14 update, many BC changes came to ERA.
At the moment itemrack seems to suffer some backdrop issues

![image](https://user-images.githubusercontent.com/10325988/135321368-bf1a393a-58d0-4c81-a524-227d933a001b.png)

Thanks for your help

**Comment by Rottenbeer** [comment]
Try this one:
[ItemRack-3.68-classic.zip](https://github.com/Rottenbeer/ItemRack/files/7357512/ItemRack-3.68-classic.zip)

**Comment by Slivo-fr** [comment]
Will do, thanks !

**Comment by Slivo-fr** [comment]
This version solves the graphic issue for me, thanks !
