### ISSUE TITLE
'ItemRack' tried to call the protected function 'PickupInventoryItem()'

### ISSUE THREAD

**Issue by Jakobud** [Rottenbeer/ItemRack#189]
ItemRack Classic 3.68 in BCC:

I've been getting this error lately, randomly:

```
5x [ADDON_ACTION_BLOCKED] AddOn 'ItemRack' tried to call the protected function 'PickupInventoryItem()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `PickupInventoryItem'
[string "@ItemRack\ItemRackEquip.lua"]:285: in function `MoveItem'
[string "@ItemRack\ItemRackEquip.lua"]:216: in function `IterateSwapList'
[string "@ItemRack\ItemRackEquip.lua"]:161: in function `LockChangedDuringSetSwap'
[string "@ItemRack\ItemRack-3.68.nil.lua"]:815: in function `func'
[string "@ItemRack\ItemRack-3.68.nil.lua"]:905: in function `OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
InCombatSkipped
```

I'm not sure what triggers this. It just happens randomly while playing. 

When this happens, one of my trinket slots becomes grey colored, I cannot activate the trinket or swap it out with anything else while in or out of combat. I get the message in the console "Itemrack: Cannot swap because not enough space" or something similar. There is plenty of room in my bags though.

![Screenshot 2021-10-01 235452](https://user-images.githubusercontent.com/87356/135706174-17848562-6f7d-4dda-b983-f826251a5747.png)

If I log out and back in, this fixes it. But I've also seen it fix itself if I ignore and keep playing for several more minutes. I'm not sure what causes it to fix itself. Maybe when another trinket in the auto queue goes off cooldown? Not sure.

I've only been getting this since the last ItemRack Classic update.

**Comment by Rottenbeer** [comment]
Please retest with 4.2
