### ISSUE TITLE
Add support for WowUp

### ISSUE THREAD

**Issue by jimsimon** [Rottenbeer/ItemRack#198]
CurseForge/Overwolf has blocked WowUp from accessing files hosted on its server. Please consider also publishing to WoWInterface or WowUpHub: https://wowup.io/guide/wowup/hub

**Comment by KevinTyrrell** [comment]
> CurseForge/Overwolf has blocked WowUp from accessing files hosted on its server. Please consider also publishing to WoWInterface or WowUpHub: https://wowup.io/guide/wowup/hub

Not the author but I had no problem downloading ItemRack-tbc through WowUp

![image](https://user-images.githubusercontent.com/12791400/170088398-5999ed3d-abd4-45b2-ab1b-f9595a277e71.png)
