### ISSUE TITLE
Attempt to access forbidden object in TBC

### ISSUE THREAD

**Issue by fireboy92k** [Rottenbeer/ItemRack#199]
Consistently getting this error:

14x ItemRack\ItemRack-3.69.nil.lua:1179: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `GetName'
[string "@ItemRack\ItemRack-3.69.nil.lua"]:1179: in function `func'
[string "@ItemRack\ItemRack-3.69.nil.lua"]:905: in function `OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 Text = <unnamed> {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 Left = <unnamed> {
 }
}

**Comment by Rottenbeer** [comment]
Please retest with 4.2
