### ISSUE TITLE
LUA error while trying to equip items from bank 

### ISSUE THREAD

**Issue by Getsmart** [Rottenbeer/ItemRack#2]
Date: 2019-09-07 23:34:57
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ItemRack\ItemRack.lua line 603:
   ContainerIDToInventoryID(): invalid container ID
Debug:
   [C]: ContainerIDToInventoryID()
   ItemRack\ItemRack.lua:603: ValidBag()
   ItemRack\ItemRack.lua:575: FindInBank()
   ItemRack\ItemRack.lua:1921: GetBankedSet()
   ItemRack\ItemRack.lua:1182:
      ItemRack\ItemRack.lua:1126

**Comment by Rottenbeer** [comment]
I can not reproduce the issue.
When I put eq in the bank and try to wear the set I get:
ItemRack: Could not find: [Berylline Pads] [Silver-thread Robe] [Scaled Leather Belt of the Owl] [Scaled Leather Leggings of the Eagle] [Durable Boots of the Owl] [Shredder Operating Gloves] [Totemic Clan Ring] [Plains Ring] [Death Speaker Scepter] [Conjurer's Cloak of the Owl] [Greenweave Branch of the Owl]

**Comment by Getsmart** [comment]
Hm ok might be incompatible with bagnon or any other addon

**Comment by Rottenbeer** [comment]
Can you try without any other addons?
