### ISSUE TITLE
Additional Titan's Grip Changes

### ISSUE THREAD

**Issue by ThisIsMakena** [Rottenbeer/ItemRack#206]
In file _ItemRackEquip.lua_ I also made these additional changes when I was hacking together my fix for titan's grip, apologies for missing these in our previous discussion.

Line 173 	

`local treatAs2H = nil`

Lines 194 - 202

```
if i==16 and ItemRack.HasTitansGrip then
	local subtype = select(7,GetItemInfo(GetContainerItemLink(bag,slot)))
	if subtype and ItemRack.NoTitansGrip[subtype] then
		treatAs2H = 1
	end
end
-- TODO: Polarms, Fishing Poles and Staves (7th GetItemInfo) cannot
-- be equipped alongside Two-Handed Axes, Two-Handed Maces and Two-Handed Swords
if (not ItemRack.HasTitansGrip or treatAs2H) and select(3,ItemRack.GetInfoByID(swap[i]))=="INVTYPE_2HWEAPON" then
```

Copy of my version so you can do a diffcheck easily:

[ItemRackEquip.lua.zip](https://github.com/Rottenbeer/ItemRack/files/9602932/ItemRackEquip.lua.zip)

**Comment by Rottenbeer** [comment]
Released with 3.71 in PR #208
