### ISSUE TITLE
ItemRack slot preview / quick swap for Rings does not list rings with Enchants

### ISSUE THREAD

**Issue by boktai1000** [Rottenbeer/ItemRack#216]
When mousing over a ring slot, I was previously an enchanter and enchanted most of my rings. They do not show up in the item preview, the enchant does not take effect but you are still able to wear the rings of course. ItemRack should continue to let you equip them since there is no negative impact from wearing one, you simply don't get the effect of the enchant that is on the ring.

Example picture here, also take a look at the amount of rings in my bag - as well as the tooltip of one that is equipped, and compare against the amount of rings in the preview (just three)

![image](https://user-images.githubusercontent.com/9054563/192433709-9e1e1aaa-3952-46a0-97f8-1646e27b7c8d.png)

**Comment by zanciikitty** [comment]
Had a very knowledgeable guildmate help me with this when I did the same thing of dropping enchanting for jewelcrafting. In the Itemrack addon's ItemRack.lua file on line 849. Add/change the end of the line to: 

`and invslot~=11 and invslot~=12 then`

**Comment by Rottenbeer** [comment]
Please retest with 4.2
