### ISSUE TITLE
Gear sets do not take into account different copies of one same item

### ISSUE THREAD

**Issue by LordLocksley** [Rottenbeer/ItemRack#219]
I've got several slots (Head / Shoulders / Legs) where I use the same item (T7) for both my main spec and my dual spec, (Feral cat DPS / Bear Tank), but with two different pieces as DPS enchants and gems are wildly different from the Tank enchants and gems.

Itemrack doesn't seem to take this into account, and switching sets equip one random copy of said items.

Could it be possible to include for future versions of the tool the ability to differentiate between several copies of one same item? (remembering which copy with which gems/enchants belogs to each set)

Thanks

**Comment by LordLocksley** [comment]
An update to this. I haven't been able to find the exact pattern, but ItemRack *do* sometimes mismatch wrong items, while in other scenarios it does work as expected.

When two identically items are completely gemmed and enchanted with different gems and enchants, ItemRack does seem to always be able to distinguish between them, but if one of the items are not either gemmed or enchanted, then sometimes it fails.

**Comment by Rottenbeer** [comment]
Please retest with 4.2
