### ISSUE TITLE
Unique (3) JC gems cause items to be skipped when swapping sets

### ISSUE THREAD

**Issue by susoi** [Rottenbeer/ItemRack#220]
Hi
I am using the unique (3) jewelcrafting gems in both my tank and my dps set. Since the gems are not placed in exactly the same itemslots it gives me error messages ("You can only equip 3 items in the Jeweler'ss Gems category"). Basically, whenever itemrack tries to equip a 4th unqiue gem it fails und skips that item. Maybe you could fix this by allowing custom equipping order per set or by tracking the error and repeating failed items at the end of the normal equip order.

Cheers

**Comment by jelmerj** [comment]
The latest release added some fixes for this. Do you still have this problem?

**Comment by Rottenbeer** [comment]
Please retest with 4.2
