### ISSUE TITLE
ItemRack Broken

### ISSUE THREAD

**Issue by FRSMichael** [Rottenbeer/ItemRack#227]
For the latest WOTLK Classic patch, ItemRack no longer loads itemsets nor does it shows different gear in the slots when hovering over the slot. Config tab is also broken/blank now as well.

**Comment by grlffchrs** [comment]
Please fix ItemRack for the latest WOTLK Classic patch. I am so accustomed to the addon and none of the alternatives does the trick for me.

**Comment by Cramerr** [comment]
I made some fixes locally that have it mostly working, the options pane is a mess though, getting nil response on RefreshplayerSpellIconInfo and I can't find any information about this call and what it may have changed it.

**Comment by Rottenbeer** [comment]
I merge #222 as soon as it's ready. It should fix the issues.

**Comment by Rottenbeer** [comment]
Please retest with 4.2
