### ISSUE TITLE
Bank bag slot IDs go too high

### ISSUE THREAD

**Issue by ABillam** [Rottenbeer/ItemRack#23]
There are only 6 bank bag slots in classic, but the addon seems to be expecting there to be 7; this is evident in ItemRack.lua, line 74, ItemRack.BankSlots.  The list should include:
-1 (the main bank container)
5, 6, 7, 8, 9, 10 (the six bank bag slots)
NOT 11 (this doesn't exist in classic)
When 11 is in the list, it throws errors when trying to interact with the bank; with 11 removed, no errors.

**Comment by Rottenbeer** [comment]
Fixed in 3.14, thanks for reporting
