### ISSUE TITLE
Button changes to 'default' icon instead of maintaining the set icon, when anything is changed within the set

### ISSUE THREAD

**Issue by telias82** [Rottenbeer/ItemRack#230]
-Have an itemrack set configured
-Select that set
-Change 1 item you're wearing
-Icon for set changes to the default itemrack icon - this didnt used to happen prior to Ulduar patch

![image](https://user-images.githubusercontent.com/55420496/213759207-d64655ef-cab2-485d-b82a-73b4bf889e0b.png)

**Comment by Road-block** [comment]
Because it was bugged. 
If you change an item you no longer have that "set" equipped and ItemRack shows the "I don't know this set" icon.

This is the correct behavior.

**Comment by Rottenbeer** [comment]
Please retest with 4.2
