### ISSUE TITLE
Not allowing save and will randomly switch sets

### ISSUE THREAD

**Issue by Brodieman** [Rottenbeer/ItemRack#233]
Sometimes when I am shuffling things (even random items not part of a set) IR will switch sets.  Now I cannot save unless I reload the UI.   Next time I try it will not save until I reload the UI again.

I am using ItemRack Classic from CurseForge.  

https://www.curseforge.com/wow/addons/itemrack-classic

**Comment by Brodieman** [comment]
Sorry, not sure this is the right ItemRack

**Comment by Rottenbeer** [comment]
Please retest with 4.2
