### ISSUE TITLE
 'GetName' bug on Season of Discovery

### ISSUE THREAD

**Issue by linkx2252** [Rottenbeer/ItemRack#241]
33x ItemRack/ItemRack.lua:1242: calling 'GetName' on bad self (Usage: local name = self:GetName())
[string "=[C]"]: in function `GetName'
[string "@ItemRack/ItemRack.lua"]:1242: in function `func'
[string "@ItemRack/ItemRack.lua"]:968: in function `OnUpdate'
[string "*ItemRack.xml:7_OnUpdate"]:1: in function <[string "*ItemRack.xml:7_OnUpdate"]:1>

Locals:
(*temporary) = SecureTransferDialog {
 0 = <userdata>
 Button2 = Button {
 }
 MoneyLabel = FontString {
 }
 CautionIcon = Texture {
 }
 Text = FontString {
 }
 Border = Frame {
 }
 Button1 = Button {
 }
}
`

**Comment by romracer** [comment]
Fixed in #264

**Comment by Rottenbeer** [comment]
Please retest with 4.2
