### ISSUE TITLE
Item does not go in that slot - CLASSIC ERA

### ISSUE THREAD

**Issue by mimixy** [Rottenbeer/ItemRack#243]
For a few months now, I receive an error when switching sets. It is intermittent. Only a /reload fixes it.
I am struggling to recreate the error. It doesn't happen during raid usually. But when I get back to my city and restock my bags with consumes, or reorder my bags, or hearth, then it somtimes happens.
![WoWScrnShot_010824_110455](https://github.com/Rottenbeer/ItemRack/assets/143043909/5c95b4a8-211b-4285-a612-b2518c27b293)

you can see here I am trying to swap my set using ItemRack, and you can see the error in the top middle of my screen.
There is no LUA error.

It looks like one of the weapon/bow slots is causing the error.
If I keep clicking the "saph" loadout repeatedly. It switches my main hand between THC and TF. and the bow slot also lights up as if it is trying to swap something onto there. I am guessing it is trying to put one of the 1h weps into the bow slot. that looks like what is happening.

**Comment by mimixy** [comment]
![WoWScrnShot_010824_110821](https://github.com/Rottenbeer/ItemRack/assets/143043909/fa48e9dc-22a3-4656-b62e-ca49416478a5)

**Comment by mimixy** [comment]
you can see the bow greyed out there. i managed to screenshot it as the swap is trying to happen. the bow goes grey briefly. indicating me to me its trying to swap something into that slot and failing

**Comment by mimixy** [comment]
![WoWScrnShot_010824_111243](https://github.com/Rottenbeer/ItemRack/assets/143043909/3896f000-e56a-478c-92f2-401447e7b66f)

**Comment by mimixy** [comment]
that is the set i am trying to equip

**Comment by Rottenbeer** [comment]
Please retest with 4.2
