### ISSUE TITLE
ItemRack adds confusing entries to tooltips on empty inventory slots

### ISSUE THREAD

**Issue by Elberet** [Rottenbeer/ItemRack#250]
In ItemRack version 3.77 (latest as of reporting this issue), when an equipment slot is empty but enabled to indicate this slot should be unequipped, ItemRack starts adding tooltips to empty itemslots, incorrectly believing that e.g. an empty bag slot is the same as an empty equipment set slot.

Symptoms:

In the options, flyout menus contain a "broken" empty option:
![grafik](https://github.com/Rottenbeer/ItemRack/assets/361662/46a43f80-3f4e-4c48-a50a-f01b4f48c083)
Additionally, the ItemRack options window shows a ranged weapon slot with the bow icon, and an ammunition slot, even tho my character is a shaman. It does, however, correctly list totems in the "bow" slot flyout menu, and correctly equips and unequips totems.

When hovering over an empty bag slot, a tooltip shows that ItemRack identifies the empty slot as an item in an equipment set:
![grafik](https://github.com/Rottenbeer/ItemRack/assets/361662/5f3b14eb-d578-490e-8feb-a5477123480d)
The erronous tooltip goes away, if no set contains any empty slots, or if all empty slots in all sets are disabled / ignored.

This error was not present in version 3.75. I am playing WoW WotLK Classic with German localization

**Comment by Elberet** [comment]
I believe the problem is related to this line:

https://github.com/Rottenbeer/ItemRack/blob/ae8532154573ea301271527ea251be6244a6df71/ItemRack/ItemRack.lua#L683

The string concatenation causes `ItemRack.GetID` to always return a string. Callers that previously tested item IDs with `itemID ~= 0` will no longer work, since that comparison is type sensitive.

**Comment by Rottenbeer** [comment]
Please retest with 4.2
