### ISSUE TITLE
UPDATE_WORLD_STATES SoD error

### ISSUE THREAD

**Issue by linkx2252** [Rottenbeer/ItemRack#253]
In season of discovery:

9x AceEvent30Frame:UnregisterEvent(): AceEvent30Frame:UnregisterEvent(): Attempt to unregister unknown event "UPDATE_WORLD_STATES"
[string "=[C]"]: in function `UnregisterEvent'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:37: in function `OnUnused'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:187: in function `UnregisterAllEvents'
[string "@SSPVP/modules/match.lua"]:70: in function `DisableModule'
[string "@SSPVP/SSPVP.lua"]:135: in function `?'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "UPDATE_WORLD_STATES"

**Comment by Rottenbeer** [comment]
Please retest with 4.2
