### ISSUE TITLE
ItemRack attempted to call a protected function (PickupInventoryItem()) during combat lockdown

### ISSUE THREAD

**Issue by diggerton** [Rottenbeer/ItemRack#26]
Date: 2019-09-17 13:37:06
ID: 1
Error occured in: AddOn: ItemRack
Count: 1
Message: Note: AddOn ItemRack attempted to call a protected function (PickupInventoryItem()) during combat lockdown.
Debug:
   [C]: PickupInventoryItem()
   ItemRack\ItemRackEquip.lua:278: MoveItem()
   ItemRack\ItemRackEquip.lua:211: IterateSwapList()
   ItemRack\ItemRackEquip.lua:113: EquipSet()
   ItemRack\ItemRackEvents.lua:348: ProcessStanceEvent()
   ItemRack\ItemRackEvents.lua:293: ProcessingFrameOnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
   [C]: CancelShapeshiftForm()
   ..\FrameXML\ChatFrame.lua:1251: ?()
   ..\FrameXML\ChatFrame.lua:4589:
      ..\FrameXML\ChatFrame.lua:4556
   [C]: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4270:
      ..\FrameXML\ChatFrame.lua:4269
   [C]: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:2699:
      ..\FrameXML\ChatFrame.lua:2692
   [C]: ?
   [C]: UseAction()
   ..\FrameXML\SecureTemplates.lua:338: handler()
   ..\FrameXML\SecureTemplates.lua:616:
      ..\FrameXML\SecureTemplates.lua:564
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:266:
      ..\FrameXML\SecureHandlers.lua:263
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:296:
      ..\FrameXML\SecureHandlers.lua:279
   (tail call): ?
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.1.11
  Bartender4, v4.8.7
  ClassicAuraDurations, v
  ClassicCastbars, vv1.0.6
  ClassicCastbarsOptions, v
  DruidMana, v1.2
  EasyFishingClassic, v1.2
  GuildTooltip, v1.1.3
  Inventorian, v1.13.2.4
  ItemRack, v
  ItemTooltipProfessionIcons, v1.1.1
  LeatrixMaps, v1.13.30
  LeatrixPlus, v1.13.30
  MissingTradeSkillsList, v1.13.07
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  NugEnergy, v1.13.7
  OmniCC, v8.2.4
  Prat30, v3.7.36
  Prat30Libraries, v
  Quartz, v3.5.1
  Questie, v4.0.18 BETA
  QuestLogEx, v1.2
  RealMobHealth, v2.11
  Recount, vv1.13.2c
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TrinketMenu, v7.3.2
  WeakAuras, v2.14.6
  WhatsTraining, v1.8.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=33c)

**Comment by Rottenbeer** [comment]
Switching weapons in combat is not working, that's a known issue right now.

**Comment by diggerton** [comment]
Copy that. I saw the other thread but in-combat weapon swapping does sometimes work, just the time it errors the most.

**Comment by Rottenbeer** [comment]
Hm? What do you mean with "sometimes work" and "just the time it errors the most?

**Comment by diggerton** [comment]
You’re right, the weapon swaps I was seeing was from an old macro I was using.

**Comment by Rottenbeer** [comment]
Retest with 3.15.
