### ISSUE TITLE
Lua Errors on Cata PTR

### ISSUE THREAD

**Issue by holypalaswe** [Rottenbeer/ItemRack#268]
657x ItemRack/ItemRack.lua:1289: attempt to call global 'GetMouseFocus' (a nil value)
[string "@ItemRack/ItemRack.lua"]:1289: in function `func'
[string "@ItemRack/ItemRack.lua"]:1016: in function `OnUpdate'
[string "*ItemRack.xml:7_OnUpdate"]:1: in function <[string "*ItemRack.xml:7_OnUpdate"]:1>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMouseFocus' (a nil value)"

**Comment by holypalaswe** [comment]
temporary fix with help from Bhahlou:
\Interface\AddOns\ItemRack\ItemRack.lua 
line 1289
replace "GetMouseFocus()" with "GetMouseFoci()[1]"
![image](https://github.com/user-attachments/assets/dbbdb6bc-c032-4ba7-9c4b-7e41f9629837)

**Comment by Rottenbeer** [comment]
Should be fixed with 4.2
