### ISSUE TITLE
Events don't work properly

### ISSUE THREAD

**Issue by futurex21** [Rottenbeer/ItemRack#27]
I tried to set up an "Event" where I equip a spirit staff for evocation then re-equip my previous MH+OH but it usually bugs out for me.

**Comment by Rottenbeer** [comment]
Switching weapons in combat does not work right now.

**Comment by Dr34ml4and3r** [comment]
> Switching weapons in combat does not work right now.

Confirm it.When you are out of combat is switches automatically with the set that was previously selected.For example, in battles stance/defensive of the warrior, first time I charge with the battle stance gear , I enter in combat and I change in defensive stance , but the set gear doesn't switch,remaining locked on the battle stance gear.It switches automatically only after I'm out of combat.

**Comment by Rottenbeer** [comment]
Retest with version 3.17 please
