### ISSUE TITLE
Error clicking on item in Trinket Queue

### ISSUE THREAD

**Issue by ejrichards** [Rottenbeer/ItemRack#29]
When I try to click on an item in the trinket queue, this error occurs and I'm unable to adjust the queue.

```
Date: 2019-09-19 10:44:38
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ItemRackOptions\ItemRackOptions.lua line 1191:
   Usage: ItemRackOptItemStatsDelay:SetText("text")
Debug:
   [C]: SetText()
   ItemRackOptions\ItemRackOptions.lua:1191: ValidateSortButtons()
   ItemRackOptions\ItemRackOptions.lua:1159: SortListOnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
(*temporary) = ItemRackOptItemStatsDelay {
 0 = <userdata>
}
(*temporary) = false
```

**Comment by AGandrup** [comment]
I managed to fix this issue by changing line 1191 from:

`		ItemRackOptItemStatsDelay:SetText((ItemRackItems[baseID] and ItemRackItems[baseID].delay) or false)`

to:

`		ItemRackOptItemStatsDelay:SetText((ItemRackItems[baseID] and ItemRackItems[baseID].delay) or "0")`

This fix allows one to put delay on item swapping as well.

**Comment by Rottenbeer** [comment]
@AGandrup nice, can you create a pull request please?

**Comment by AGandrup** [comment]
Sure, there you go. Pretty simple fix.
