### ISSUE TITLE
[SoD] Unrecognized XML: Backdrop

### ISSUE THREAD

**Issue by gurka** [Rottenbeer/ItemRack#290]
After today's patch there are a bunch of lua warnings immediately after logging in to the game (SoD), all related to the `<Backdrop>` element at https://github.com/Rottenbeer/ItemRack/blob/3dcc1ffd8954e434ed68c77b1efe0ecd3fca4281/ItemRack/ItemRack.xml#L17

I guess that `<Backdrop>` has been deprecated?

**Comment by cloudbells** [comment]
See https://github.com/Rottenbeer/ItemRack/pull/291

**Comment by gurka** [comment]
Fixed by https://github.com/Rottenbeer/ItemRack/pull/291

**Comment by Rottenbeer** [comment]
Thanks anyways!
