### ISSUE TITLE
Rune of the Guard Captain

### ISSUE THREAD

**Issue by harrisonzalman** [Rottenbeer/ItemRack#30]
The Horde-only trinket 'Rune of the Guard Captain' (link to the item below) does not appear in the trinket drop down when it is in your bags. It seems to be not considered a trinket.

https://classic.wowhead.com/item=19120/rune-of-the-guard-captain

**Comment by Rottenbeer** [comment]
Is it soulbound to you?

**Comment by harrisonzalman** [comment]
Yes it is soulbound

**Comment by gcaliber** [comment]
Mine is shown and works fine. If you hold alt do you see it? In that case you accidentally hid it.

**Comment by harrisonzalman** [comment]
I did accidentally hide it - thanks!
