### ISSUE TITLE
Addon doesn't work properly with a bank open

### ISSUE THREAD

**Issue by rbarcc** [Rottenbeer/ItemRack#31]
Hi, I wish that while interacting with a bank the addon would pick items from bank and stash currently equipped items in the same bank slots.

Currently I have to dump all my bank inventory into my bag, close the bank, equip through addon, and then stash everything back to the bank again, I have like 4 different sets of equipment so clicking all that gear back and forth takes a lot of time. Storing all that gear in my bags is not an option because while AoE grinding every inventory slot matters.

**Comment by Rottenbeer** [comment]
While at a bank:

Items/sets in the bank have a blue border.
Selecting an item or set that's in the bank will pull it from the bank to your bags.
Selecting an item or set that's not in the bank will attempt to put it all into the bank.

Video:  https://www.youtube.com/watch?v=d_hrJKNtUfU
