### ISSUE TITLE
might be me not sure 

### ISSUE THREAD

**Issue by kraemder** [Rottenbeer/ItemRack#33]
I made a set and then got a new item and went into the set to change out the head piece for the new item.  It seems to save but when I use the set it puts the head piece on for 1 second and then switches back to the old headpiece.
*edit*
ok I found a setting called enable auto queues which is on by default and turning that off fixed it.  I have no idea what autoqueues are.

**Comment by Rottenbeer** [comment]
Autoqueues are a feature that can be enabled/disabled with alt clicking on slots (sse here https://www.curseforge.com/wow/addons/itemrack).
Just disable it again.
