### ISSUE TITLE
"One-handed" weapon WILL freeze slots midcombat

### ISSUE THREAD

**Issue by raven0ak** [Rottenbeer/ItemRack#36]
If you try to swap "one-handed" weapon to either main or offhand slots middle of combat, itemrack will grey out both slots and you need to unlock em manually with two-handed weapon or forced "mainhand" or "offhand" (eg shield)

**Comment by Rottenbeer** [comment]
Switching weapons in combat is not supported right now

**Comment by boktai1000** [comment]
Yeah, this is incredibly annoying - you can't even drag a one hander into your off hand once it greys out too. The only way I've been able to fix (due to the items I carry around) is a /reload

**Comment by Rottenbeer** [comment]
Retest with 3.19 please
