### ISSUE TITLE
Swaping off-hand midcombat doesen't work

### ISSUE THREAD

**Issue by OhNardo** [Rottenbeer/ItemRack#38]
It greys out and freezes for some reason.

![lel](https://user-images.githubusercontent.com/43202841/65905472-e6fbd300-e3c0-11e9-90f1-5a6181e1a3fb.PNG)

**Comment by gcaliber** [comment]
You cannot use addons to change equipment during combat in classic, for that you have to use a macro.

**Comment by mcfry** [comment]
A quick fix to have it swap when out of combat (better than nothing) is to remove the swappable=true option from line 90 in ItemRack.lua

This prevents it from getting stuck in the grey/locked state

New line is:
`[17] = { name="SecondaryHandSlot", real="Off hand", INVTYPE_WEAPON=1, INVTYPE_WEAPONOFFHAND=1, INVTYPE_SHIELD=1, INVTYPE_HOLDABLE=1, other=16 },`

Also, for my understanding, does one of the API functions simply not work while in combat?

**Comment by gcaliber** [comment]
The latest version doesn't check the swappable flag at all, so you may be using an older one. Not sure if you need the latest from github or if that version was released on addon sites.

And yes, the API needed to pickup and/or swap items is combat locked by Blizzard.

**Comment by mcfry** [comment]
It's used here: https://github.com/Rottenbeer/ItemRack/blob/9869e26242d9e924994495a2574519a83792ded9/ItemRack/ItemRack.lua#L1187-L1189

**Comment by boktai1000** [comment]
The greyed out bug for my off hand / shield is becoming problematic while raiding. Is there any way this change can be implemented to at least improve on the current situation? Thank you!

**Comment by Rottenbeer** [comment]
I removed it in 3.19, please retest.
