### ISSUE TITLE
Trinket/Carrot Not Swapping Back After Demount

### ISSUE THREAD

**Issue by Daiei808** [Rottenbeer/ItemRack#39]
Trinket will switch to carrot when mounted, but will not switch back after I demount.  Anyone know why?

**Comment by gcaliber** [comment]
The bug is with using the option for "any mount." Edit the mounted event to only be for the mount you are using and seems to work properly.

**Comment by Daiei808** [comment]
Tried that and still not working. Once it switches to carrot it will never switch back.

I've moved on to "AutoCarrot" add on for now. It works flawlessly but is only for mount purposes.

**Comment by Rottenbeer** [comment]
Retest with version 3.17 please
