### ISSUE TITLE
Feature Request: Modify Show Helm/Cape with Equipped sets

### ISSUE THREAD

**Issue by pbjtime** [Rottenbeer/ItemRack#41]
An option when building a gear set to have a show cloak and show helm option to switch this around based on sets would be awesome!

**Comment by Rottenbeer** [comment]
I don't plan to add features, sorry.

**Comment by pbjtime** [comment]
Are you considering allowing other devs to work on this? I would be willing to contribute here...

**Comment by flmei** [comment]
Feel free to send me a PR, I already accepted other PRs :)

**Comment by Rottenbeer** [comment]
I already accepted other pull requests, so feel free to contribute
