### ISSUE TITLE
Stops working and have to log out and back in to fix

### ISSUE THREAD

**Issue by Spiritualjedi** [Rottenbeer/ItemRack#42]
Date: 2019-10-06 04:14:26
ID: 1
Error occured in: AddOn: ItemRack
Count: 1
Message: Note: AddOn ItemRack attempted to call a protected function (UNKNOWN()) during combat lockdown.
Debug:
   [C]: ?
   [C]: ?
   [C]: PickupInventoryItem()
   ItemRack\ItemRackEquip.lua:267: MoveItem()
   ItemRack\ItemRackEquip.lua:200: IterateSwapList()
   ItemRack\ItemRackEquip.lua:145: LockChangedDuringSetSwap()
   ItemRack\ItemRack.lua:696: func()
   ItemRack\ItemRack.lua:786: OnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdiBags, vDEV
  AdvancedInterfaceOptions, v1.3.3
  AtlasLootClassic, vv1.2.2
  AtlasLootClassicDungeonsAndRaids, vv1.2.2
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BlizzMove, v1.9
  DBMCore, v1.13.13b
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElvUI, v1.01
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  FieldGuide, vv1.5-release
  FishingBuddy, v0.6 Beta 1
  FiveSecondRule, v1.1
  GrimoireKeeper, v1.1
  GTFO, v4.50.1
  Guidelime, v1.032
  GuidelimeBusteas160leveling, v1.7.0-Release
  GuidelimeSage, v1.0
  HandyNotes, vv1.5.6
  HandyNotesDungeonLocationsClassic, v1.03
  HandyNotesFlightMastersClassic, v1.06
  HandyNotesNPCsClassic, v1.16
  HandyNotesTravelGuideClassic, vv2.1.4
  IceHUD, v1.12.7
  InFlightLoad, v1.13.003
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.33
  MissingTradeSkillsList, v1.13.18
  MonkeyBuddy, v
  MonkeyClock, vv3.2.0
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  MonkeySpeed, vv3.4.0
  Necrosis, v5.0
  NugComboBar, v1.13.3
  NugEnergy, v1.13.10
  OmniBar, vv10.3
  OmniCC, v8.2.5
  orbSellAndRepair, v1.0.1
  Pawn, v2.3.7
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v4.1.1 BETA
  SexyMap, vv3-classic
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SimpleDing, vv1.1.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SoulSpeak, v8.04-classic
  SpeedyAutoLoot, v2.0.20
  Spy, v1.0.9
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.2.4
  TinyTooltip, v8.2.1
  TitanClassic, v1.1.1.11302
  TitanClassicAmmo, v1.1.1.11302
  TitanClassicBag, v1.1.1.11302
  TitanClassicClock, v1.1.1.11302
  TitanClassicGold, v1.1.1.11302
  TitanClassicLocation, v1.1.1.11302
  TitanClassicLootType, v1.1.1.11302
  TitanClassicPerformance, v1.1.1.11302
  TitanClassicRegen, v1.1.0.11302
  TitanClassicRepair, v1.1.1.11302
  TitanClassicVolume, v1.1.1.11302
  TitanClassicXP, v1.1.1.11302
  TomTom, vv11302-1.0.7
  TradeSkillMaster, vv4.8.14
  TradeSkillMasterAppHelper, vv4.0.5
  VendorPrice, v1.2.9
  WeakAuras, v2.15.2
  WeaponSwingTimer, v4.1.0
  WideQuestLog, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=a28)

**Comment by Rottenbeer** [comment]
Switching items in combat will not work, since the call is made protected by Blizzard.
