### ISSUE TITLE
Unable to keybind to Mouse 3 through 5

### ISSUE THREAD

**Issue by ngrayson** [Rottenbeer/ItemRack#43]
In Slot Key Bindings, you are unable to bind to mouse 3 through 5, or alt/ctrl of those binds

This addon is amazing though, thank you so much for your hard work

**Comment by Rottenbeer** [comment]
Retest with 3.18

**Comment by ngrayson** [comment]
thank you

**Comment by Rottenbeer** [comment]
Does it work for you?

**Comment by ngrayson** [comment]
It does not

**Comment by Rottenbeer** [comment]
Which version did you test?
Does not even button 3 and 4 work for you?
I tested it and it worked for me...

**Comment by ngrayson** [comment]
I tested with 3.19 and neither button 3 nor 4 nor 5 work
