### ISSUE TITLE
Auto-Mount doesn't automatically swap sometimes

### ISSUE THREAD

**Issue by Dizeliun** [Rottenbeer/ItemRack#44]
Auto-Dismount seems bugged, works sometimes, doesn't work other times, sometimes only swaps half my items, sometimes constantly swaps my items over and over and over until I physically turn the addon off. Please fix, we need a working auto-swap addon in classic!

**Comment by Rottenbeer** [comment]
Which version did you test?
Can you try to use the actual mount name instead of the "any mount"?
