### ISSUE TITLE
ActionBar buttons disable and get the following error:

### ISSUE THREAD

**Issue by Sanguinius45** [Rottenbeer/ItemRack#46]
Date: 2019-10-10 20:28:05
ID: 1
Error occured in: Global
Count: ∞
Message: ..\AddOns\ItemRack\ItemRackEvents.lua line 242:
   Attempt to register unknown event "ACTIVE_TALENT_GROUP_CHANGED"
Debug:
   [C]: RegisterEvent()
   ItemRack\ItemRackEvents.lua:242: RegisterEvents()
   ItemRack\ItemRackEvents.lua:213: InitEvents()
   ItemRack\ItemRack.lua:183: func()
   ItemRack\ItemRack.lua:786: OnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
(*temporary) = ItemRackEventProcessingFrame {
 0 = <userdata>
}
(*temporary) = "ACTIVE_TALENT_GROUP_CHANGED"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ArkInventory, v30903
  ArkInventoryRules, v20000
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v20000
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.2.3
  AtlasLootClassicDungeonsAndRaids, vv1.2.3
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  DBMCore, v1.13.15
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  Questie, v4.1.2 BETA 121 dff5a12
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=411)

**Comment by Rottenbeer** [comment]
Tested version?

**Comment by Rottenbeer** [comment]
ACTIVE_TALENT_GROUP_CHANGED is not used in the current version of itemrack, did you install the classic version?
