### ISSUE TITLE
Mounted Gear Swap Back

### ISSUE THREAD

**Issue by pcastracucco** [Rottenbeer/ItemRack#53]
It appears that the item swap back is bugged using the mounted event. I've tried setting it to the buff id as well as buff name instead of just any mount. The gear I had on previously does not reequip.

**Comment by jelgh** [comment]
This happens if you do an action right after the event, you cant swap gear on global cooldown. At least that's what i noticed

**Comment by Rottenbeer** [comment]
Please retest with version 3.30
