### ISSUE TITLE
rogue weapon swapping with stealth event

### ISSUE THREAD

**Issue by ianhutson** [Rottenbeer/ItemRack#54]
i want to use itemrack to automatically swap my dagger and sword when i stealth. it works beautifully when i stealth, my dagger goes to my MH as intended. however, after i backstab (or ambush, he's still a low level), it doesn't swap back. it DOES swap back after combat, but that defeats the purpose. can anyone help?

**Comment by Rottenbeer** [comment]
Swapping weapons in combat will never work with events

**Comment by ianhutson** [comment]
cheers
