### ISSUE TITLE
error with icons

### ISSUE THREAD

**Issue by Finrodi** [Rottenbeer/ItemRack#56]
`2x [ADDON_ACTION_BLOCKED] AddOn 'ItemRack' tried to call the protected function 'SetBindingClick()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetBindingClick'
ItemRack\ItemRack-3.23.nil.lua:1884: in function `SetSetBindings'
ItemRack\ItemRack-3.23.nil.lua:434: in function `InitCore'
ItemRack\ItemRack-3.23.nil.lua:202: in function `func'
ItemRack\ItemRack-3.23.nil.lua:846: in function `OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
InCombatSkipped`

https://i.imgur.com/QLi5X3n.png

**Comment by Rottenbeer** [comment]
Saving keybinds in combat is not possible.

**Comment by Finrodi** [comment]
Never setup keybinds during combat, must come from something else. Its not like i setup my hotkeys 24/7 and I did clear my bugsack just recently :p
