### ISSUE TITLE
Separate queues for every set?

### ISSUE THREAD

**Issue by hasnogaems** [Rottenbeer/ItemRack#59]
Would've been awesome

**Comment by Rottenbeer** [comment]
Sorry, won't be added, I don't maintain the addon anymore.
What use case do you solve with the queue feature?

**Comment by brzGatsu** [comment]
This would be absolutely great. As a warrior I have different on-use trinkets depending on the equipped set.
- Fire resist gear (heart of the scale)
- Tank gear (later with bwl: life giving gem)
- AoE tank gear (rammsteins lightning bolts, heart of the scale)
- PvP gear (signet and engineer stuff)
- Conflicts between gears: Blackhands breath is shared between dps gear and PvP gear, however in PvP gear its only equipped as last item after all on-use items are on cd. However, in dps gear I always want blackhands breath, so I have to disable auto-queue there.

**Comment by Rottenbeer** [comment]
@brzGatsu thanks for explaining the use cases.
I will not add this though, since I don't maintain the addon anymore.

**Comment by hasnogaems** [comment]
@brzGatsu @Rottenbeer Maybe there is some other addon with item que functionality that can help?
