### ISSUE TITLE
Questystem broken with item/itemslot

### ISSUE THREAD

**Issue by Finrodi** [Rottenbeer/ItemRack#62]
Queuesystem doesn't seem to work for certain items or slots.

It works here when the "Ornate Mithril Boots" is on cd:

https://i.imgur.com/dvOoiRs.png

But it doesn't work here when "Spider Belt" is on cd: 

https://i.imgur.com/hJcLi0s.png

I know you discontinued the addon but a fix for this would be very much appreciated.

**Comment by Rottenbeer** [comment]
I'm sorry, but I wont fix it, since I discontinued the work on the addon.
If you can try to fix the issue, I will review and accept the pull request.
