### ISSUE TITLE
Disabling Events Not Working for Mounted Event

### ISSUE THREAD

**Issue by shakesx** [Rottenbeer/ItemRack#68]
With the latest commit (3/28), disabling events does not disable the Mounted event. Even if you disable events, it will still equip the set for the Mounted event when mounting.

EDIT: I also tried resetting events to default and recreating them, and the issue remained.

**Comment by Rottenbeer** [comment]
Can you try the lastest version of the addon from github?
I don't have a WoW account since half a year, so I can't test it.

**Comment by shakesx** [comment]
The issue has been fixed, thank you for the prompt response!
