### ISSUE TITLE
[lua error]

### ISSUE THREAD

**Issue by Altoholic** [Rottenbeer/ItemRack#69]
1x [ADDON_ACTION_BLOCKED] AddOn 'ItemRackOptions' tried to call the protected function 'PickupMacro()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `PickupMacro'
[string "*:OnDragStart"]:1: in function <[string "*:OnDragStart"]:1>

**Comment by Rottenbeer** [comment]
I'm sorry, but I wont fix it, since I discontinued the work on the addon.
If you can try to fix the issue, I will review and accept the pull request.
