### ISSUE TITLE
Mounted Gear doesn't unswap reliably

### ISSUE THREAD

**Issue by ysaliens** [Rottenbeer/ItemRack#71]
The addon works fairly reliably for mount/dismount switching between a PVP and a Riding set of gear (trinket, boots, gloves part of each set).

However, it occasionally bugs and does not unswap one of the items when attacked by a mob while riding. When you dismount...the addon attempts to unswap but you're in combat so it can't and queues the swaps. When the combat ends and the addon is able to swap gear, it tries swapping but often times fails to swap one or two of the items.

Example:
1. Riding a mount with "Mount" set equipped.
2. Mob attacks you. You dismount and kill mob.
3. Addon fails to swap one or more pieces of the PvP set and leaves the "Mount" set gear on.

**Comment by ysaliens** [comment]
Please either fix the bug or break up the mount event into a mount and a dismount event that the addon can treat separately. That way on unmount (and not in combat) the addon would attempt to swap a specific set.

**Comment by Rottenbeer** [comment]
should be fixed with 3.30
