### ISSUE TITLE
Symbols in set names 

### ISSUE THREAD

**Issue by erounsavall** [Rottenbeer/ItemRack#74]
I noticed strange behaviors and traced it to having a set named +healing. (It maximizes the +healing bonuses on my gear)

I also had a set named 'hybrid' and when I equipped it some of the gear would revert to some of the gear chosen in the +healing set (specifically Gloves of Restoration, for example). Or if I tried to switch Gloves of Restoration to any other gloves manually, they would switch back. There are no events associated with either set. I also reloaded UI, checked version, restarted game, etc. 

I renamed the +healing set to just healing and ItemRack now behaves as expected.

**Comment by Rottenbeer** [comment]
I guess it's similar to issue#57, but I wont fix it, since I discontinued the work on the addon.
If you can try to fix the issue, I will review and accept the pull request.
