### ISSUE TITLE
Set/equipment changes not queing while in combat

### ISSUE THREAD

**Issue by nerolite** [Rottenbeer/ItemRack#82]
Whenever I am in combat and trigger an equipment change (e.g. swap to a set with a different trinket, or my fire resistance set) I expect this action to be queued and performed as soon as I leave combat. This is not occurring. The equipment change is only attempted immediately as I press the button, and is not queued. Is this a bug on my end, or is this how the addon is set up to function?

Scenario: I would like to manually queue up a trinket change to my on-use trinket while clearing trash, which will then swap immidiately as I leave combat.

**Update 2020-05-03**
It would appear this behavior is related to the _auto queue_ functionality. When this is turned off, manually queuing sets while in combat works as expected. Is there any way for these two functionalities to work simultaneously?

**Comment by Rottenbeer** [comment]
> It would appear this behavior is related to the auto queue functionality. When this is turned off, manually queuing sets while in combat works as expected. Is there any way for these two functionalities to work simultaneously?

I never tried this, I only fixed the basic functionality of the addon for classic and I don't play WoW anymore.
