### ISSUE TITLE
Toggle not toggling

### ISSUE THREAD

**Issue by nforbus** [Rottenbeer/ItemRack#9]
I have two sets created on my warrior;

- Shield
- DualWield

Using the macro; 

/itemrack toggle Shield, DualWield

When I first used ItemRack the other day, this macro worked just fine.  Now when I use it, it will gladly put me in Shield, but will not swap back to DualWield.  I don't get any error messages either, it just doesn't work... I can still manually swap to both armor sets via the minimap button as well.

**Comment by Rottenbeer** [comment]
what version did you test?

**Comment by jnday** [comment]
I was having the same problem as @nforbus after downloading the latest from wowinterface.com, and using your latest github version fixed this for me.

**Comment by nforbus** [comment]
3.10 - I will also try out the version jnday referred to and see if it fixes it.

**Comment by Rottenbeer** [comment]
Retest with 3.15.
