### ISSUE TITLE
taint when load addon during combat

### ISSUE THREAD

**Issue by iwowui** [Rottenbeer/ItemRack#90]
my modified version:

`
ItemRack.InitButtons() in ItemRackButtons.lua
local ircb = CreateFrame("Frame");
function ItemRack.InitButtons()
	if InCombatLockdown() then
		ircb:RegisterEvent("PLAYER_REGEN_ENABLED");
		ircb:SetScript("OnEvent", function(self, event)
			ItemRack.InitButtons();
			ircb:UnregisterEvent("PLAYER_REGEN_ENABLED");
		end)
		return;
	end
    ...
end

ItemRack.SetSetBindings() in ItemRack.lua
local ircb = CreateFrame("Frame");
function ItemRack.SetSetBindings()
	if InCombatLockdown() then
		ircb:RegisterEvent("PLAYER_REGEN_ENABLED");
		ircb:SetScript("OnEvent", function(self, event)
			ItemRack.SetSetBindings();
			ircb:UnregisterEvent("PLAYER_REGEN_ENABLED");
		end)
		return;
	end
    ...
end
`

**Comment by Rottenbeer** [comment]
Hi
Can you send a pull request please?
