### ISSUE TITLE
Default Nefarian Event not working

### ISSUE THREAD

**Issue by Shardot** [Rottenbeer/ItemRack#93]
The default Nefarian event for detecting when you enter Nefarian's lair doesn't seem to be working. I believe that the issue is that it's watching the wrong zone change trigger, but I haven't verified it in the code. The following works as a script if you have a set named Nefarian, but having the default working would be better:

**Event Trigger:** ZONE_CHANGED_INDOORS
**Event Script:**
if GetSubZoneText() == "Nefarian's Lair" then 
EquipSet("Nefarian")
else
UnequipSet("Nefarian")
end

**Comment by Rottenbeer** [comment]
Hi

Please download https://github.com/Rottenbeer/ItemRack/tree/nefarian-lair-beta and test if it works as expected.
I also take indoor zone changes into account now.
I cannot test it on my own, since I stopped playing wow.

**Comment by Shardot** [comment]
Doesn't quite seem to help sadly. It seems to have improved the situation somewhat, as it now autoequips the set if you log out in Nefarian's lair and then log back in, and correctly restores it if you run out of Nefarian's lair and then logout followed by login.

Also corrrectly unequips the Nefarian set when hearthstoning/teleporting out. But the detection of changes while in the zone doesn't seem to be working yet. I appreciate your effort though.

**Comment by Rottenbeer** [comment]
hmmm strange, I kinda did what you also said up there in this commit:
https://github.com/Rottenbeer/ItemRack/commit/8982690b00a8e4c953d5e5106129a7fa46fc5117
Maybe you can have a look if I missed something?

**Comment by Rottenbeer** [comment]
@Shardot Please retest the branch again, I just pushed an update.

**Comment by Shardot** [comment]
The latest version seems to be working. Kudos. :)

**Comment by Rottenbeer** [comment]
I'll fixed it in 3.39, release should be up soon.
